apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    image.opencontainers.org/created: "2020-02-06T13:52:44-05:00"
    stack.appsody.dev/configured: docker.io/appsody/java-microprofile:0.2
    stack.appsody.dev/created: 2019-11-26T15:01:00+0000
    stack.appsody.dev/revision: 697abc712b0ee47832d1016bbf0d1b5d50129338
    stack.appsody.dev/tag: appsody/java-microprofile:0.2.21
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: sample-java-microprofile
    stack.appsody.dev/version: 0.2.21
  name: sample-java-microprofile
spec:
  applicationImage: dev.local/sample-java-microprofile
  createKnativeService: true
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 9080
    type: NodePort
  stack: java-microprofile
  version: 1.0.0
status: {}
